### ISSUE TITLE
Revise "Configuration" chapters regarding Docker installation

### ISSUE THREAD

**Issue by JanCBrammer** [ComPlat/chemotion_saurus#116]
@ptrxyz, as pointed out by @alhoch, https://chemotion.net/chemotionsaurus/docs/eln/settings needs to be updated w.r.t., the Docker installation. Currently, the information pertains to local installs.

**Comment by harivyasi** [comment]
Unfortunately editing the online pages is taking more time then expected because we are in the process of linking them to the versioning system of Chemotion.

Meanwhile, in order to edit the files mentioned on the [settings](https://chemotion.net/chemotionsaurus/docs/eln/settings), page, one can follow the following steps:

1. Download the example file(s) that you wish to modify from the branch of your Chemotion version. The generic link to the file(s) is `https://github.com/ComPlat/chemotion_ELN/tree/v<your_version_of_chemotion>/config/<filename>.example`. Save the file(s) in a location where you can edit it (them). For example, we will save it in the `~/Downloads` folder.
2. Edit the file(s) as required and explained on the [settings](https://chemotion.net/chemotionsaurus/docs/eln/settings) page.

If you HAVE `admin` privileges:

3. Go to the folder where you have your `docker-compose.yml` file. Here you should have a folder called `shared`. 
4. Make yourself an admin using the `sudo su` command.
5. Use the command `mkdir -p shared/pullin/config` to make the `config` folder if it doesn't exist.
6. Copy your file(s) into this folder e.g. `cp ~/Downloads/user_props.yml.example shared/pullin/config/user_props.yml`.
7. Make the file(s) owned by root i.e. `chown 0:0 shared/pullin/config/user_props.yml`
8. Restart the instance using `docker compose restart`.

If you DO NOT HAVE `admin` privileges:

3. Make sure that your instance of Chemotion is running. Then determine the `CONTAINER ID` of the `eln` container using the command: ` docker ps --filter NAME="eln"`. Take care to identify the correct container ID if the output lists multiple containers.
4. Use this container ID to copy the file(s) into the container. For example if the container ID is `88e778e80a`, the command to copy `user_props.yml.example` into the container would be `docker cp ~/Downloads/user_props.yml.example 88e778e80a:/chemotion/app/config/user_props.yml`.
5. Restart the instance using `docker compose restart` command in the folder that stores your `docker-compose.yml` file.
6. Using this (second) method does not preserve your configuration between upgrades of Chemotion. So please make a backup of your configuration file(s) and copy them into the container after every upgrade. If this is cumbersome, please contact us to fix it more permanently.

**Comment by harivyasi** [comment]
@JanCBrammer do we close this? File specific instructions are now available [here](https://chemotion.net/docs/eln/install_configure/configuration#configuration-in-chemotion-eln), but suggestions to improve this are welcome :)

**Comment by JanCBrammer** [comment]
@harivyasi, :+1:  for closing this.
